version: '2'
services:
  mongodb:
    image: mongo:3.4.13
    volumes:
      - ./mongodb:/data/db
    ports:
      - 127.0.0.1:27017:27017
  webapp:
    image: node:10.6.0 # Alpine cannot be used, because git executable is needed
    volumes:
      - ./webapp:/src
    command: "bash -c 'yarn install && yarn run dev'"
    working_dir: /src
  api:
    image: zeta-sbt:1.0.6
    build: ./api
    volumes:
      - ./api:/app
      - ./sbt/server:/root
    environment:
      - APPLICATION_SECRET=XXXXX
      - ZETA_MONGODB_SERVER=mongodb
      - ZETA_DEPLOYMENT=production
    stdin_open: true
    ports:
      - 80:9000
    links:
      - mongodb
      - webapp
    command: ["-Dlogger.play=ERROR","-Dlogger.application=ERROR","-Dzeta.webapp.host=webapp", "project server", "run"]