version: '3'
services:
  game_module:
    image: game_module:v1
    stdin_open: true
    ports:
      - 9001:9001
    networks:
      default:
        aliases:
          - mygame

  player_module:
    image: player_module:v1
    ports:
      - 9000:9000
    networks:
      default:
        aliases:
          - myplayer

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      default:
        aliases:
          - mymongo
